### PR TITLE
Save selected Server IP Address in a binary file called "serverIpAddress.hex"

### PR DESCRIPTION
**Pull request by Yardape8000**
The FS folder is from loadiine_gx2.  Only the files needed to mount SD are used.
I believe I added mount/unmount in the best location in main.c.

### CODE REVIEW

**Comment by CuriousTommy** [comment]
@Yardape8000 Out of curiosity, where is this file stored in the SD card? (I am not related to the people behind this software, I am just curious)

**Comment by djskual** [comment]
"sd:/wiiu/apps/ddd/serverIpAddress.hex"

**Comment by dimok789** [comment]
Great, thanks. Though why did you decide to store it in binary. Lets just store it as string in a text file. I think that is more user friendly. If you want to do it go ahead. Otherwise I will merge your pull request and adapt it.

**Comment by Yardape8000** [comment]
I left it as binary, because it was the easiest to save and I figured it could easily be modified when ddd starts.  Feel free to modify it.

**Comment by dimok789** [comment]
Alright. The code looks good for now. I might change it to string in the future though.

**Comment by Touristos** [comment]
Hi,

Thank you for your work.
after Using the v0.3 release and dumping MK8 code folder, i don't found the serverIpAddress.hex in my sd:/wiiu/apps/ddd/.
Is it normal or have i made something wrong.

Thanks for revert
Regards

**Comment by ultra-azu** [comment]
It will come in ddd v0.4 or ddd 0.3 rc_4. If you can't hesitate, then go compile it from source.
That means it is normal.

**Pull request merged**
